name: Ubuntu
on: [push]
jobs:
  ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
      # print Ubuntu version
      - run: cat /etc/lsb-release
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: lastName=Smith
        env:
          CYPRESS_firstName: Joe

  ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      # print Ubuntu version
      - run: cat /etc/lsb-release
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: lastName=Smith
        env:
          CYPRESS_firstName: Joe
